export const memberships = {
  "initial-care": {
    name: "Focused Care Membership",
    eyebrow: "Essential ongoing care",
    headline: "Keep one treatment pathway connected.",
    price: "$149/month",
    cadence: "monthly",
    image: "/membership-initial-care-v1.png",
    intro: "Focused ongoing clinical support for patients who want one treatment pathway managed simply and consistently.",
    features: ["Included 15-minute initial appointment", "Scheduled clinician follow-up", "Prescription and refill management", "Focused progress monitoring"],
    cta: "Choose Focused Care",
    includesComprehensiveVisit: false,
  },
  treatment: {
    name: "Apex Treatment Membership",
    eyebrow: "Keep your progress moving",
    headline: "Your treatment. Connected.",
    price: "From $499/month",
    annual: "From $4,990/year — 2 months free",
    image: "/membership-treatment-v1.png",
    intro: "Broader clinical attention for patients managing multiple goals, treatments, or health priorities.",
    features: ["Everything in Focused Care", "Included 45-minute comprehensive initial appointment after enrollment", "Longer, broader clinical reviews", "Multi-treatment coordination", "More frequent treatment-response review", "Clinically appropriate adjustments"],
    cta: "Choose Apex Treatment",
    includesComprehensiveVisit: true,
  },
  performance: {
    name: "Apex Performance Membership",
    eyebrow: "Built for more",
    headline: "Raise your level.",
    price: "From $749/month",
    annual: "From $7,490/year — 2 months free",
    image: "/membership-performance-diverse-v2.png",
    intro: "Elevated access and a deeper focus on performance, prevention, and long-term progress.",
    features: ["Everything in Apex Treatment Membership", "Included 45-minute comprehensive initial appointment after enrollment", "Monthly progress reviews", "Priority scheduling, subject to availability", "Extended appointments", "Quarterly comprehensive reviews", "Lifestyle and nutrition guidance", "Performance optimization planning"],
    cta: "Choose Apex Performance",
    includesComprehensiveVisit: true,
  },
  "private-client": {
    name: "Apex Private Client Care",
    eyebrow: "Limited enrollment",
    headline: "Care designed around you.",
    price: "From $1,250/month",
    annual: "From $12,500/year — 2 months free",
    image: "/membership-private-v1.png",
    intro: "Concierge-level care for people who value exceptional access, privacy, and proactive coordination.",
    features: ["Everything in Apex Performance", "Included 45-minute comprehensive initial appointment after enrollment", "Frequent scheduled strategy visits", "Proactive laboratory and pharmacy coordination", "Concierge-level continuity", "A care cadence designed around your goals"],
    cta: "Choose Private Client Care",
    includesComprehensiveVisit: true,
  },
} as const;

export type MembershipSlug = keyof typeof memberships;
